### ISSUE TITLE
There is no working folder mapping

### ISSUE THREAD

**Issue by Manikese** [Jezusfan/MultiMerge#5]
Trying to "Unshelve to branch..." and getting a popup MessageBox with the following message text:  "There is no working folder mapping for $/<source_dir>/<modified_file>."

I've tried different workspaces, global workspaces, and different shelvesets in different branches.  The error is the same for each attempt with the only difference being the filename that is one of the files in a shelveset.

Old versions of this extension have worked great for me in the past.  This 2022 version does not work in my Visual Studio Professional 2022 though.  Version 17.6.2   .NET Version 4.8.09032   Source Control:  Azure DevOps Server
![Screenshot 2024-01-22 162132](https://github.com/Jezusfan/MultiMerge/assets/9417182/27d3a05c-df97-4520-bafb-b65a4594c63c)

**Comment by RobSiklos** [comment]
I have the same error, and would love for this to be fixed. I know that sometimes older TFS client libraries can't recognize workspaces created with newer versions of TFS. Could that be related?

**Comment by WalterWigman-Iress** [comment]
I'd love to work on this, but I no longer have access to TSF. If you have time, it may be quite easy to fix this issue yourselves. There's a Winforms test UI (shares a UI-control with the VS-plugin), which lets you pick a source-controlled working folder and acts as if you're using the plugin in Visual Studio. So your problem is easily debuggable, if you have access to a TFS server.

**Comment by Manikese** [comment]
Thank you for getting back to us!I’ll have to try debugging against the TFS server if I can get access.  I’ll let you know. With honor and admiration,-JeffOn Jan 24, 2024, at 5:08 PM, Walter Wigman ***@***.***> wrote:﻿
I'd love to work on this, but I no longer have access to TSF. If you have time, it may be quite easy to fix this issue yourselves. There's a Winforms test UI (shares a UI-control with the VS-plugin), which lets you pick a source-controlled working folder and acts as if you're using the plugin in Visual Studio. So your problem is easily debuggable, if you have access to a TFS server.
